language: node_js
sudo: false
node_js:
  - 12
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Typecheck
      name: dts
      script: make test-types

    - stage: Unit Test
      name: jest
      script: make test-ci
