name: Create GitHub Release
on:
  push:
    tags:
      - 'v*'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          version=$(echo ${${{ github.ref }}/v/})
          changes=$(sed -n "/^### Version $version/,/^###/p" CHANGELOG.md | sed '$d' | sed '1d')
          links=$(cat CHANGELOG.md | grep '^\[')
          echo "::set-output name=name::$version"
          echo "::set-output name=changes::${changes//$'\n'/%0A}"
          echo "::set-output name=links::${links//$'\n'/%0A}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.prep.outputs.name }}
          body: |
            ${{ steps.prep.outputs.changes }}
            ${{ steps.prep.outputs.links }}
          draft: false
          prerelease: true
